# Generated by Django 4.2.13 on 2024-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
